---
repo-name: peripherals-aws-ec2
categories:
  - Cloud
  - DevOps
display-name: Amazon EC2
manufacturer: Amazon
description: Amazon Elastic Compute Cloud (Amazon EC2) is a web service that provides secure, scalable compute capacity in the cloud.
